name: Deploy to Firebase Hosting on merge

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current project revision
        uses: actions/checkout@v3

      - name: Configure Node.js on runner
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install package dependencies using lockfile
        run: npm i

      - run: npm run deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEVFEST_SD_22 }}'
          channelId: live
          projectId: devfest-sd-23
